spring:
  datasource:
    url: jdbc:mysql://localhost:3306/govtech
    username: root
    password: passw0rd4
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

## App Properties
app:
  jwtSecret: I2NvbS5iZWUuQnJhaW5DaGVja2VyQDIwMjMxMDA1MTcyNiM=
  jwtExpirationInSeconds: 600
  jwtRefreshTokenExpirationInSeconds: 1200
  jwtIssuer: localhost.sg
  jwtCookieName: govtech-access-token
  jwtRefreshCookieName: govtech-refresh-token
  maxLoginAttempts: 5